#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
iw dev wlan0 interface add uap0 type __ap
sysctl net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -s 192.168.50.0/24 ! -d 192.168.50.0/24 -j MASQUERADE
# write the first part of the conf file
echo -en 'interface=uap0\nssid=PFC MVP v1.0\ndriver=nl80211\nhw_mode=g\nieee80211n=1\nchannel=' > /etc/hostapd/hostapd.conf
iwlist channel 2> /dev/null | awk '/Current/ {print substr($5,1,length($5) - 1)}' >> /etc/hostapd/hostapd.conf
echo -e 'macaddr_acl=0\nauth_algs=1\nignore_broadcast_ssid=0\nwpa=2\nctrl_interface=/var/run/hostapd\nctrl_interface_group=0' >> /etc/hostapd/hostapd.conf
echo -e 'wpa_passphrase=12345678\nwpa_key_mgmt=WPA-PSK\nwpa_pairwise=TKIP\nrsn_pairwise=CCMP' >> /etc/hostapd/hostapd.conf
ifdown wlan0
ip link set dev uap0 up
ip addr add 192.168.50.1/24 broadcast 192.168.50.255 dev uap0
sleep 1
# start hostapd
hostapd -B -P /run/hostapd.pid /etc/hostapd/hostapd.conf &
sleep 1
service hostapd restart
ifup wlan0
service dnsmasq restart
